apiVersion: v1
kind: Service
metadata:
  name: {{ include "onix-kafka.fullname" . }}-{{ .Values.component }}-service
  labels:
    {{- include "onix-kafka.labels" . | nindent 4 }}
    component: {{ .Values.component }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.otel.enabled (gt (int .Values.otel.metricsPort) 0) }}
    - port: {{ .Values.otel.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "onix-kafka.selectorLabels" . | nindent 4 }}
    component: {{ .Values.component }}

